version: 2
updates:
  - package-ecosystem: pip
    directory: /packages/python
    schedule: {interval: weekly}
  - package-ecosystem: npm
    directory: /packages/typescript
    schedule: {interval: weekly}
  - package-ecosystem: mix
    directory: /packages/elixir
    schedule: {interval: weekly}
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
